CREATE TABLE IF NOT EXISTS urls (
                                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    original_url TEXT NOT NULL,
                                    short_code TEXT UNIQUE NOT NULL
);